export const latexSymbols: Record<string, string> = {
  // Greek letters (lowercase)
  "\\alpha": "α",
  "\\beta": "β", 
  "\\gamma": "γ",
  "\\delta": "δ",
  "\\epsilon": "ε",
  "\\varepsilon": "ε",
  "\\zeta": "ζ",
  "\\eta": "η",
  "\\theta": "θ",
  "\\vartheta": "ϑ",
  "\\iota": "ι",
  "\\kappa": "κ",
  "\\lambda": "λ",
  "\\mu": "μ",
  "\\nu": "ν",
  "\\xi": "ξ",
  "\\pi": "π",
  "\\varpi": "ϖ",
  "\\rho": "ρ",
  "\\varrho": "ϱ",
  "\\sigma": "σ",
  "\\varsigma": "ς",
  "\\tau": "τ",
  "\\upsilon": "υ",
  "\\phi": "φ",
  "\\varphi": "ϕ",
  "\\chi": "χ",
  "\\psi": "ψ",
  "\\omega": "ω",

  // Greek letters (uppercase)
  "\\Gamma": "Γ",
  "\\Delta": "Δ",
  "\\Theta": "Θ",
  "\\Lambda": "Λ",
  "\\Xi": "Ξ",
  "\\Pi": "Π",
  "\\Sigma": "Σ",
  "\\Upsilon": "Υ",
  "\\Phi": "Φ",
  "\\Psi": "Ψ",
  "\\Omega": "Ω",

  // Mathematical operators
  "\\pm": "±",
  "\\mp": "∓",
  "\\times": "×",
  "\\div": "÷",
  "\\cdot": "⋅",
  "\\ast": "∗",
  "\\star": "⋆",
  "\\circ": "∘",
  "\\bullet": "∙",
  "\\oplus": "⊕",
  "\\ominus": "⊖",
  "\\otimes": "⊗",
  "\\oslash": "⊘",
  "\\odot": "⊙",
  "\\bigcirc": "◯",
  "\\dagger": "†",
  "\\ddagger": "‡",
  "\\amalg": "⨿",

  // Relations
  "\\leq": "≤",
  "\\le": "≤",
  "\\geq": "≥",
  "\\ge": "≥",
  "\\neq": "≠",
  "\\ne": "≠",
  "\\equiv": "≡",
  "\\approx": "≈",
  "\\cong": "≅",
  "\\simeq": "≃",
  "\\sim": "∼",
  "\\propto": "∝",
  "\\prec": "≺",
  "\\succ": "≻",
  "\\preceq": "⪯",
  "\\succeq": "⪰",
  "\\ll": "≪",
  "\\gg": "≫",
  "\\subset": "⊂",
  "\\supset": "⊃",
  "\\subseteq": "⊆",
  "\\supseteq": "⊇",
  "\\nsubseteq": "⊈",
  "\\nsupseteq": "⊉",
  "\\in": "∈",
  "\\ni": "∋",
  "\\notin": "∉",
  "\\perp": "⊥",
  "\\parallel": "∥",
  "\\vdash": "⊢",
  "\\dashv": "⊣",

  // Arrows
  "\\leftarrow": "←",
  "\\gets": "←",
  "\\rightarrow": "→",
  "\\to": "→",
  "\\leftrightarrow": "↔",
  "\\uparrow": "↑",
  "\\downarrow": "↓",
  "\\updownarrow": "↕",
  "\\Leftarrow": "⇐",
  "\\Rightarrow": "⇒",
  "\\Leftrightarrow": "⇔",
  "\\Uparrow": "⇑",
  "\\Downarrow": "⇓",
  "\\Updownarrow": "⇕",
  "\\mapsto": "↦",
  "\\longmapsto": "⟼",
  "\\hookleftarrow": "↩",
  "\\hookrightarrow": "↪",
  "\\leftharpoonup": "↼",
  "\\rightharpoonup": "⇀",
  "\\leftharpoondown": "↽",
  "\\rightharpoondown": "⇁",
  "\\rightleftharpoons": "⇌",

  // Set theory
  "\\emptyset": "∅",
  "\\varnothing": "∅",
  "\\cap": "∩",
  "\\cup": "∪",
  "\\setminus": "∖",
  "\\complement": "∁",

  // Logic
  "\\neg": "¬",
  "\\lnot": "¬",
  "\\land": "∧",
  "\\lor": "∨",
  "\\wedge": "∧",
  "\\vee": "∨",
  "\\exists": "∃",
  "\\forall": "∀",
  "\\top": "⊤",
  "\\bot": "⊥",

  // Calculus
  "\\partial": "∂",
  "\\nabla": "∇",
  "\\infty": "∞",
  "\\int": "∫",
  "\\oint": "∮",
  "\\sum": "∑",
  "\\prod": "∏",
  "\\coprod": "∐",

  // Other symbols
  "\\sqrt": "√",
  "\\degree": "°",
  "\\angle": "∠",
  "\\measuredangle": "∡",
  "\\sphericalangle": "∢",
  "\\triangle": "△",
  "\\square": "□",
  "\\lozenge": "◊",
  "\\blacksquare": "■",
  "\\blacktriangle": "▲",
  "\\blacktriangledown": "▼",
  "\\clubsuit": "♣",
  "\\diamondsuit": "♦",
  "\\heartsuit": "♥",
  "\\spadesuit": "♠",
  "\\sharp": "♯",
  "\\flat": "♭",
  "\\natural": "♮",

  // Miscellaneous
  "\\aleph": "ℵ",
  "\\hbar": "ℏ",
  "\\ell": "ℓ",
  "\\wp": "℘",
  "\\Re": "ℜ",
  "\\Im": "ℑ",
  "\\mho": "℧",
  "\\Finv": "Ⅎ",
  "\\Game": "⅁",
  "\\Bbbk": "𝕜",
  "\\backprime": "‵",
  "\\Box": "□",
  "\\Diamond": "◊",
  "\\leadsto": "↝"
};

export const symbolDescriptions: Record<string, string> = {
  "\\alpha": "Greek letter alpha",
  "\\beta": "Greek letter beta",
  "\\gamma": "Greek letter gamma", 
  "\\delta": "Greek letter delta",
  "\\epsilon": "Greek letter epsilon",
  "\\theta": "Greek letter theta",
  "\\lambda": "Greek letter lambda",
  "\\mu": "Greek letter mu",
  "\\pi": "Greek letter pi",
  "\\sigma": "Greek letter sigma",
  "\\phi": "Greek letter phi",
  "\\omega": "Greek letter omega",
  "\\pm": "Plus-minus sign",
  "\\times": "Multiplication sign",
  "\\div": "Division sign",
  "\\leq": "Less than or equal to",
  "\\geq": "Greater than or equal to",
  "\\neq": "Not equal to",
  "\\approx": "Approximately equal to",
  "\\equiv": "Equivalent to",
  "\\in": "Element of",
  "\\subset": "Subset of",
  "\\supset": "Superset of",
  "\\leftarrow": "Left arrow",
  "\\rightarrow": "Right arrow",
  "\\leftrightarrow": "Left-right arrow",
  "\\Rightarrow": "Right double arrow (implies)",
  "\\Leftrightarrow": "Left-right double arrow (if and only if)",
  "\\infty": "Infinity",
  "\\partial": "Partial derivative",
  "\\nabla": "Nabla (del operator)",
  "\\int": "Integral",
  "\\sum": "Summation",
  "\\prod": "Product",
  "\\sqrt": "Square root",
  "\\forall": "For all",
  "\\exists": "There exists",
  "\\emptyset": "Empty set",
  "\\cap": "Intersection",
  "\\cup": "Union"
};
